# -*- coding: utf-8 -*-
"""regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ig5FPnq-jM7dx-F6ZPqRj3XOEcAYbU9
"""

#library
import numpy as np
from sklearn.linear_model import LinearRegression

import joblib

#dataset 
import pandas as pd
df=pd.read_csv('/content/Hotel.csv', sep=",")

x = np.array(df.iloc[:,1]).reshape((-1, 1))

y = np.array(df.iloc[:,0])

#call model regression
model = LinearRegression().fit(x,y)

#save model
filename = 'model.sav'
joblib.dump(model, filename)

#load model
loaded_model = joblib.load(filename)

#prediction model
loaded_model.predict(20)